### ISSUE TITLE
Fix integration

### ISSUE THREAD

**Issue by rarbg** [verybada/rarbgsubscriber#9]
Hello
Please integrate the API instead of calling directly the site
https://torrentapi.org/apidocs_v2.txt

**Comment by verybada** [comment]
@rarbg 
Thanks for opening apis, I'll refactory my code asap. 

Are there any paging parameter I can user for search/list?

**Comment by rarbg** [comment]
@verybada api was never closed :) 

We dont support any type of paging

**Comment by verybada** [comment]
@rarbg 

So, there is no way to get a torrent once it is not in top 100?

**Comment by rarbg** [comment]
@verybada did you even read the API docs ?

**Comment by verybada** [comment]
@rarbg 

yes, I saw there is a parameter 'limit' and only 25, 50 and 100, that makes me confused.

For example, seems I don't have the way to get last 200 torrents. that's why I'm asking for paging api.

**Comment by rarbg** [comment]
@verybada 
You cannot get the last 200 torrents. There is no paging api.
But you can get the latest 100 per category. With 20 categories thats 2000

**Comment by verybada** [comment]
@rarbg 

Understood. Thanks for explanation.

**Comment by verybada** [comment]
Use official API already

**Comment by verybada** [comment]
@rarbg 
does the API down? I got 403 forbidden for almost two weeks

**Comment by rarbg** [comment]
What user agent are you using ?

**Comment by verybada** [comment]
What do you mean about the agent?

I use both python requests and chrome to test API with get_token and  them all got 403 forbiden and become 200 Invalid API parameters! today

**Comment by rarbg** [comment]
If you don't reply to my questions there is no way to help you

**Comment by verybada** [comment]
Do you mean the http header 'user-agent'? I don't give this header

**Comment by rarbg** [comment]
Yes thats what user agent is.
Start providing it to the API
Also check what request parameters you are missing from the docs

**Comment by verybada** [comment]
I made a request like this
```
GET https://torrentapi.org/pubapi_v2.php?get_token=get_token
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
```

and still get `Invalid API parameters!`, Am I missing something?

**Comment by rarbg** [comment]
Yes you did
1. Your user agent shouldn't be spoofed. CF will start doing captcha 
checks from time to time making the API unusable for anyone using 
rarbgsubscriber if you do that
2. You missed the first line of the docs - app_id

**Comment by verybada** [comment]
Thanks for your suggestion. I'm going to check them again.
